import { DI } from 'core'
import { ORDER_STATUS, RED_STATUS, EXCHANGE_ORDER_STATUS, WITHDRAW_ORDER_STATUS } from './order'
import { BI_TYPE,
  BI_IMG,
  BT_INIT_BUY_NUM,
  BI_MIN_BUY_AMOUNT,
  BI_WITHDRAW_ACTION_FEE,
  BI_WITHDRAW_MIN_AMOUNT,
  BI_TOFIX_NUMBER,
  BI_DISABLE_WITHDRAW,
  BI_MAX_BUY_AMOUNT,
  BI_DISABLE_DEPOSIT,
  BI_DISABLE_BUY,
  BI_NAME,
  BI_INFO,
  BI_NY_COINID,
  BI_LOCAL_ICON,
  PAIR_MARKET_PRICE_NY_SUPPORT_OTC,
  AGGREGATE_TRANS_SUPPORT_OTC,
  OTC_INFO
} from './bi'
import { CUSTOMER_SERVICE_WECHAT,
  CUSTOMER_SERVICE_WECHAT_QRCODE,
  CUSTOMER_SECURITY_LEVEL
} from './customer'
import { VIP_YUBIBAO_LIMIT, VIP_YUBIBAO_ADD_INTEREST, VIP_AIR } from './vip'
import { RANKING_LABEL_DATA } from './ranking'
import { STOCK_CO_INFO } from './stock'

DI.bindValue('ORDER_STATUS', ORDER_STATUS)
DI.bindValue('BI_DISABLE_BUY', BI_DISABLE_BUY)
DI.bindValue('EXCHANGE_ORDER_STATUS', EXCHANGE_ORDER_STATUS)
DI.bindValue('WITHDRAW_ORDER_STATUS', WITHDRAW_ORDER_STATUS)
DI.bindValue('BI_TYPE', BI_TYPE)
DI.bindValue('BI_IMG', BI_IMG)
DI.bindValue('BT_INIT_BUY_NUM', BT_INIT_BUY_NUM)
DI.bindValue('BI_MIN_BUY_AMOUNT', BI_MIN_BUY_AMOUNT)
DI.bindValue('BI_MAX_BUY_AMOUNT', BI_MAX_BUY_AMOUNT)
DI.bindValue('BI_WITHDRAW_ACTION_FEE', BI_WITHDRAW_ACTION_FEE)
DI.bindValue('BI_DISABLE_DEPOSIT', BI_DISABLE_DEPOSIT)
DI.bindValue('BI_WITHDRAW_MIN_AMOUNT', BI_WITHDRAW_MIN_AMOUNT)
DI.bindValue('BI_NAME', BI_NAME)
DI.bindValue('BI_DISABLE_WITHDRAW', BI_DISABLE_WITHDRAW)
DI.bindValue('BI_TOFIX_NUMBER', BI_TOFIX_NUMBER)
DI.bindValue('RED_STATUS', RED_STATUS)
DI.bindValue('BI_INFO', BI_INFO)
DI.bindValue('BI_NY_COINID', BI_NY_COINID)
DI.bindValue('OTC_INFO', OTC_INFO)
DI.bindValue('PAIR_MARKET_PRICE_NY_SUPPORT_OTC', PAIR_MARKET_PRICE_NY_SUPPORT_OTC)
DI.bindValue('AGGREGATE_TRANS_SUPPORT_OTC', AGGREGATE_TRANS_SUPPORT_OTC)
DI.bindValue('BI_LOCAL_ICON', BI_LOCAL_ICON)
DI.bindValue('CUSTOMER_SERVICE_WECHAT', CUSTOMER_SERVICE_WECHAT)
DI.bindValue('CUSTOMER_SERVICE_WECHAT_QRCODE', CUSTOMER_SERVICE_WECHAT_QRCODE)
DI.bindValue('CUSTOMER_SECURITY_LEVEL', CUSTOMER_SECURITY_LEVEL)
DI.bindValue('VIP_YUBIBAO_LIMIT', VIP_YUBIBAO_LIMIT)
DI.bindValue('VIP_YUBIBAO_ADD_INTEREST', VIP_YUBIBAO_ADD_INTEREST)
DI.bindValue('VIP_AIR', VIP_AIR)
DI.bindValue('RANKING_LABEL_DATA', RANKING_LABEL_DATA)
DI.bindValue('STOCK_CO_INFO', STOCK_CO_INFO)
