"""empty message

Revision ID: 4a81a0ab56b1
Revises: 1379ca5fef51
Create Date: 2021-01-18 20:42:52.724477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a81a0ab56b1'
down_revision = '1379ca5fef51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('cn_fullname', sa.String(length=64), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_coin_name'), 'coin', ['name'], unique=False)
    op.create_table('coin_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=32), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_favorite_customer_id'), 'coin_favorite', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coin_favorite_slug'), 'coin_favorite', ['slug'], unique=False)
    op.create_index(op.f('ix_coin_favorite_status'), 'coin_favorite', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_favorite_status'), table_name='coin_favorite')
    op.drop_index(op.f('ix_coin_favorite_slug'), table_name='coin_favorite')
    op.drop_index(op.f('ix_coin_favorite_customer_id'), table_name='coin_favorite')
    op.drop_table('coin_favorite')
    op.drop_index(op.f('ix_coin_name'), table_name='coin')
    op.drop_table('coin')
    # ### end Alembic commands ###
